[package]
name = "openssl"
version = "0.9.13"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "Apache-2.0"
description = "OpenSSL bindings"
repository = "https://github.com/sfackler/rust-openssl"
documentation = "https://docs.rs/openssl/0.9.13/openssl"
readme = "../README.md"
keywords = ["crypto", "tls", "ssl", "dtls"]
categories = ["cryptography", "api-bindings"]
build = "build.rs"

[features]
v101 = []
v102 = []
v110 = []

[dependencies]
bitflags = "0.9"
foreign-types = "0.2"
lazy_static = "0.2"
libc = "0.2"
openssl-sys = { version = "0.9.13", path = "../openssl-sys" }

[dev-dependencies]
tempdir = "0.3"
winapi = "0.2"
ws2_32-sys = "0.2"
hex = "0.2"
