[package]
name = "openssl"
version = "0.10.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "Apache-2.0"
description = "OpenSSL bindings"
repository = "https://github.com/sfackler/rust-openssl"
readme = "README.md"
keywords = ["crypto", "tls", "ssl", "dtls"]
categories = ["cryptography", "api-bindings"]
build = "build.rs"

[package.metadata.docs.rs]
all-features = true

[features]
v101 = []
v102 = []
v110 = []
v111 = []

[dependencies]
bitflags = "1.0"
foreign-types = "0.3.1"
lazy_static = "1"
libc = "0.2"
openssl-sys = { version = "0.9.25", path = "../openssl-sys" }

[dev-dependencies]
tempdir = "0.3"
hex = "0.3"
data-encoding = "2.0"
